-- 관리프로그램 탭 관련 MEXERCISEPROGRAM_HM 테이블 생성 및 확인(남)
CREATE TABLE MEXERCISEPROGRAM_HM(
    EXERCISENUM     NUMBER(3) PRIMARY KEY,
    PROGRAMDAY      NUMBER(2),
    EXERCISENAME    VARCHAR2(60),
    EXERCISEVOLUME  VARCHAR2(60)
);

SELECT * FROM MEXERCISEPROGRAM_HM;
DESC MEXERCISEPROGRAM_HM;


-- 남자 운동 관리 프로그램 데이터 저장 SQL문

-- 1주차
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(1, 1, '인클라인 푸시업', '3세트 (15회, 13회, 12회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(2, 1, '디클라인 푸시업', '3세트 (15회, 13회, 12회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(3, 1, '덤벨 컬', '3세트 (6KG 10회, 6KG 10회, 8KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(4, 1, '크런치', '3세트 (15회씩)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(5, 2, '딥스', '3세트 (12회, 10회, 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(6, 2, '사이드 레트럴 레이즈', '3세트 (6KG 15회씩)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(7, 2, '벤트 오버 레트럴 레이즈', '3세트 (6KG 15회씩)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(8, 2, '케틀벨 스쿼트', '3세트 (12KG 15회씩)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(9, 3, '턱걸이(친업)', '3세트 (5회씩)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(10, 3, '렛풀 다운', '3세트 (세트마다 증량 - 12회, 10회, 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(11, 3, '케틀벨 스쿼트', '3세트 (12KG 15회씩)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(12, 3, '레그 익스텐션', '3세트 (세트마다 증량 - 12회, 10회, 10회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(13, 4, '덤벨 컬', '3세트 (6KG 10회, 6KG 10회, 8KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(14, 4, '해머 컬', '3세트 (6KG 10회, 6KG 10회, 8KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(15, 4, '벤치 딥스', '3세트 (15회, 13회, 12회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(16, 4, '킥 백', '3세트 (4KG 12회, 4KG 12회, 6KG 10회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(17, 5, '딥스', '3세트 (12회, 10회, 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(18, 5, '케틀벨 스쿼트', '3세트 (12KG 20회씩)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(19, 5, '턱걸이(친업)', '3세트 (5회씩)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(20, 5, '라잉 레그 레이즈', '3세트 (15회씩)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(21, 6, '덤벨 컬', '3세트 (6KG 10회, 6KG 10회, 8KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(22, 6, '벤치 딥스', '3세트 (15회, 13회, 12회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(23, 6, '턱걸이(친업)', '3세트 (5회씩)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(24, 6, '케틀벨 스쿼트', '3세트 (12KG 20회씩)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(25, 7, '런닝(달리기)', '40분');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(26, 7, '스트레칭', '20분');

-- 2주차
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(27, 8, '딥스', '3세트 (14회, 13회, 12회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(28, 8, '디클라인 푸시업', '3세트 (20회, 17회, 15회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(29, 8, '덤벨 컬', '3세트 (6KG 10회, 6KG 10회, 8KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(30, 8, '해머 컬', '3세트 (6KG 10회, 6KG 10회, 8KG 8회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(31, 9, '턱걸이(친업)', '3세트 (6회, 6회, 5회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(32, 9, '렛풀 다운', '3세트 (세트마다 증량 - 12회, 10회, 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(33, 9, '원암 트라이셉스 익스텐션', '3세트 (6KG 10회, 6KG 10회, 8KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(34, 9, '벤치 딥스', '3세트 (15회, 13회, 12회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(35, 10, '케틀벨 스쿼트', '3세트 (12KG 20회, 16KG 15회, 12KG 15회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(36, 10, '프런트 런지', '3세트 (10KG 12회, 12KG 10회, 14KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(37, 10, '레그 익스텐션', '3세트 (세트마다 증량 - 12회, 10회, 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(38, 10, '레그 컬', '3세트 (세트마다 증량 - 12회, 10회, 10회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(39, 11, '프런트 레트럴 레이즈', '3세트 (8KG 15회, 10KG 13회, 12KG 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(40, 11, '사이드 레트럴 레이즈', '3세트 (6KG 15회, 6KG 15회, 8KG 13회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(41, 11, '벤트 오버 레트럴 레이즈', '3세트 (4KG 15회, 4KG 15회, 6KG 13회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(42, 11, '아놀드 프레스', '3세트 (6KG 12회, 6KG 12회, 8KG 10회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(43, 12, '딥스', '3세트 (14회, 13회, 12회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(44, 12, '케틀벨 스쿼트', '3세트 (12KG 20회, 16KG 15회, 12KG 15회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(45, 12, '턱걸이(친업)', '3세트 (6회, 6회, 5회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(46, 12, '크런치', '3세트 (15회씩)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(47, 13, '타바타 루틴 1', '3라운드');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(48, 14, '런닝(달리기)', '40분');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(49, 14, '스트레칭', '20분');

-- 3주차
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(50, 15, '플랫 벤치 프레스', '4세트 (40KG 10회, 50KG 8회, 60KG 7회, 40KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(51, 15, '플랫 덤벨 프레스', '4세트 (12KG 12회, 14KG 10회, 16KG 8회, 12KG 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(52, 15, '바벨 컬', '4세트 (10KG 10회, 10KG 10회, 15KG 8회, 10KG 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(53, 15, '프리쳐 컬', '4세트 (4KG 10회, 4KG 10회, 6KG 8회, 4KG 10회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(54, 16, '턱걸이(풀업)', '4세트 (5회, 5회, 3회, 3회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(55, 16, '원암 덤벨로우', '4세트 (10KG 12회, 12KG 10회, 14KG 8회, 10KG 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(56, 16, '케이블 트라이셉스 프레스 다운', '4세트 (세트마다 증량 - 12회, 10회, 8회, 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(57, 16, '다이아몬드 푸시업', '4세트 (12회, 12회, 10회, 10회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(58, 17, '바벨 백 스쿼트', '4세트 (50KG 10회, 60KG 8회, 70KG 7회, 50KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(59, 17, '백 런지', '4세트 (10KG 12회, 12KG 10회, 14KG 8회, 10KG 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(60, 17, '레그 익스텐션', '4세트 (세트마다 증량 - 12회, 10회, 8회, 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(61, 17, '레그 컬', '4세트 (세트마다 증량 - 12회, 10회, 8회, 10회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(62, 18, '덤벨 숄더 프레스', '4세트 (8 KG 12회, 10 KG 10회, 12 KG 8회, 8 KG 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(63, 18, '아놀드 프레스', '4세트 (6KG 12회, 8KG 10회, 10KG 8회, 6KG 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(64, 18, '행잉 레그 레이즈', '4세트 (10회, 10회, 8회, 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(65, 18, '크런치', '4세트 (20회, 20회, 15회, 15회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(66, 19, '플랫 벤치 프레스', '4세트 (40KG 10회, 50KG 8회, 60KG 7회, 40KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(67, 19, '바벨 백 스쿼트', '4세트 (50KG 10회, 60KG 8회, 70KG 7회, 50KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(68, 19, '턱걸이(풀업)', '4세트 (5회, 5회, 3회, 3회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(69, 19, '행잉 레그 레이즈', '4세트 (10회, 10회, 8회, 8회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(70, 20, '타바타 루틴 2', '3라운드');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(71, 21, '런닝(달리기)', '40분');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(72, 21, '스트레칭', '20분');

-- 4주차
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(73, 22, '플랫 벤치 프레스', '4세트 (50KG 10회, 60KG 8회, 65KG 7회, 50KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(74, 22, '인클라인 벤치 프레스', '4세트 (30KG 10회, 35KG 8회, 40KG 7회, 30KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(75, 22, '바벨 컬', '4세트 (10KG 10회, 15KG 10회, 15KG 8회, 10KG 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(76, 22, '해머 컬', '4세트 (6KG 12회, 8KG 10회, 10KG 8회, 6KG 10회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(77, 23, '턱걸이(풀업)', '4세트 (5회씩)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(78, 23, '바벨 로우', '4세트 (30KG 10회, 35KG 8회, 40KG 7회, 30KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(79, 23, '라잉 트라이셉스 익스텐션', '4세트 (10KG 10회, 15KG 10회, 20KG 6회, 10KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(80, 23, '케이블 트라이셉스 프레스 다운', '4세트 (세트마다 증량 - 12회, 10회, 8회, 10회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(81, 24, '바벨 백 스쿼트', '4세트 (55KG 10회, 65KG 8회, 75KG 7회, 55KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(82, 24, '레그 프레스', '4세트 (세트마다 증량 - 12회, 10회, 8회, 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(83, 24, '백 런지', '4세트 (10KG 12회, 12KG 10회, 14KG 8회, 10KG 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(84, 24, '스티프', '4세트 (40KG 10회, 50KG 10회, 60KG 8회, 40KG 10회)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(85, 25, '덤벨 숄더 프레스', '4세트 (10KG 12회, 12KG 10회, 14KG 8회, 10KG 10회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(86, 25, '사이드 레트럴 레이즈', '4세트 (6KG 20회씩)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(87, 25, '행잉 레그 레이즈', '4세트 (10회씩)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(88, 25, '크런치', '4세트 (20회씩)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(89, 26, '플랫 벤치 프레스', '4세트 (50KG 10회, 60KG 8회, 65KG 7회, 50KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(90, 26, '바벨 로우', '4세트 (30KG 10회, 35KG 8회, 40KG 7회, 30KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(91, 26, '바벨 백 스쿼트', '4세트 (55KG 10회, 65KG 8회, 75KG 7회, 55KG 8회)');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(92, 26, '행잉 레그 레이즈', '4세트 (10회씩)');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(93, 27, '타바타 루틴 3', '3라운드');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(94, 28, '런닝(달리기)', '40분');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(95, 28, '스트레칭', '20분');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(96, 29, '자전거타기', '20분');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(97, 29, '계단오르기', '20분');

INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(98, 30, '런닝(달리기)', '40분');
INSERT INTO MEXERCISEPROGRAM_HM (EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(99, 30, '스트레칭', '20분');

COMMIT

-- 관리프로그램 탭 관련 WEXERCISEPROGRAM_HM 테이블 생성 및 확인(여)
CREATE TABLE WEXERCISEPROGRAM_HM(
    EXERCISENUM     NUMBER(3)   PRIMARY KEY,
    PROGRAMDAY      NUMBER(2),
    EXERCISENAME    VARCHAR2(60),
    EXERCISEVOLUME  VARCHAR2(60)
);
DROP TABLE WEXERCISEPROGRAM_HM;

-- 여자 운동 관리 프로그램 데이터 저장 SQL문
/*1일차*/
SELECT * FROM WEXERCISEPROGRAM_HM;
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(1, 1, '플랭크', '30초씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(2, 1, '브릿지 ', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(3, 1, '스쿼트', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(4, 1, '포워드 밴드', '20초 3세트');

/*2일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(5, 2, '런닝(달리기)', '20분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(6, 2, '스쿼트', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(7, 2, '런지', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(8, 2, '잔발뛰기', '30초씩 3세트');

/*3일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(9, 3, '플랭크', '35초씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(10, 3, '런지', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(11, 3, '브릿지', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(12, 3, '다노 종아리 스트레칭', '15분');

/*4일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(13, 4, '런닝(달리기)', '20분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(14, 4, '브릿지', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(15, 4, '스쿼트', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(16, 4, '포워드 밴드', '20초씩 3세트');

/*5일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(17, 5, '플랭크', '40초씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(18, 5, '스쿼트', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(19, 5, '런지', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(20, 5, '잔발뛰기', '30초씩 3세트');

/*6일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(21, 6, '타바타 1주차', '3라운드');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(22, 6, '다노 종아리 스트레칭', '15분');

/*7일차 - 휴식기라서 운동 없음*/

/*8일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(23, 8, '펭귄운동', '3분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(24, 8, '런지', '20개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(25, 8, '브릿지', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(26, 8, '포워드 밴드', '30초씩 3세트');

/*9일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(27, 9, '런닝(달리기)', '20분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(28, 9, '브릿지', '20개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(29, 9, '스쿼트', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(30, 9, '잔발뛰기', '40초씩 3세트');

/*10일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(31, 10, '암 서클스', '10바퀴 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(32, 10, '스쿼트', '20개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(33, 10, '런지', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(34, 10, '다노 종아리 스트레칭', '15분');

/*11일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(35, 11, '런닝(달리기)', '20분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(36, 11, '런지', '20개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(37, 11, '브릿지', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(38, 11, '포워드 밴드', '30초 3세트');

/*12일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(39, 12, '크런치', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(40, 12, '브릿지', '20개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(41, 12, '스쿼트', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(42, 12, '잔발뛰기', '40초 3세트');

/*13일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(43, 13, '타바타 2주차', '3라운드');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(44, 13, '다노 종아리 스트레칭', '15분');

/*14일차 - 휴식기라서 운동 없음*/

/*15일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(45, 15, '플랭크', '45초씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(46, 15, '브릿지', '20개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(47, 15, '와이드 스쿼트', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(48, 15, '다운 도그', '20초 3세트');

/*16일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(49, 16, '런닝(달리기)', '30분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(50, 16, '스쿼트', '20개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(51, 16, '사이드 런지', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(52, 16, '잔발뛰기', '50초 3세트');

/*17일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(53, 17, '크런치', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(54, 17, '런지', '20개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(55, 17, '덩키킥', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(56, 17, '다노 종아리 스트레칭', '15분');

/*18일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(57, 18, '런닝(달리기)', '30분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(58, 18, '브릿지', '20개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(59, 18, '와이드 스쿼트', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(60, 18, '다운 도그', '20초 3세트');

/*19일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(61, 19, '암 서클스', '10바퀴씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(62, 19, '스쿼트', '20개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(63, 19, '사이드 런지', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(64, 19, '잔발뛰기', '50초씩 3세트');

/*20일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(65, 20, '타바타 3주차', '3라운드');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(66, 20, '강하나 스트레칭', '15분');

/*21일차 -  휴식기라서 운동 없음*/

/*22일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(67, 22, '플랭크', '50초씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(68, 22, '브릿지', '30개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(69, 22, '와이드 스쿼트', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(70, 22, '다운도그', '30초씩 3세트');

/*23일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(71, 23, '달리기(러닝머신)', '30분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(72, 23, '스쿼트', '30개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(73, 23, '사이드 런지', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(74, 23, '다노 종아리 스트레칭', '15븐');

/*24일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(75, 24, '니 푸시업', '10개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(76, 24, '런지', '30개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(77, 24, '덩키킥', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(78, 24, '잔발뛰기', '60초씩 3세트');

/*25일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(79, 25, '달리기(러닝머신)', '30분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(80, 25, '브릿지', '30개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(81, 25, '사이드 런지', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(82, 25, '다운 도그', '30초씩 3세트');

/*26일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(83, 26, '크런치', '15개 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(84, 26, '스쿼트', '30개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(85, 26, '덩키킥', '15개씩 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(86, 26, '강하나 스트레칭', '15분');

/*27일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(87, 27, '타바타 4쥬처', '3라운드');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(88, 27, '다운 도그', '30초씩 3세트');

/*28일차 - 휴식기라서 운동 없음*/

/*29일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(89, 29, '펭귄운동', '3분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(90, 29, '자전거타기', '20분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(91, 29, '빨리걷기', '20분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(92, 29, '강하나 스트레칭', '15분');

/*30일차*/
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(93, 30, '암 서클스', '10바퀴 3세트');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(94, 30, '산책', '20분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(95, 30, '계단 오르기', '20분');
INSERT INTO WEXERCISEPROGRAM_HM(EXERCISENUM, PROGRAMDAY, EXERCISENAME, EXERCISEVOLUME)
VALUES(96, 30, '강하나 스트레칭', '15분');


CREATE TABLE MEXERCISEPROGRAM_HM(
    EXERCISENUM     NUMBER(3),
    PROGRAMDAY      NUMBER(2),
    EXERCISENAME    VARCHAR2(60),
    EXERCISEVOLUME  VARCHAR2(60)
);
DROP TABLE MEXERCISEPROGRAM_HM;

COMMIT;
